name: Tests

on: [ push, pull_request ]

jobs:
    build:
        runs-on: 'ubuntu-latest'
        strategy:
            matrix:
                php-versions: [ '8.3', '8.4' ]

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup PHP with PCOV
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: pcov
                    tools: composer

            -   name: Refresh lock file to match composer.json
                run: composer update --prefer-dist --no-progress --no-interaction

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Dump Autoload
                run: composer dump-autoload

            -   name: Run linter
                run: ./vendor/bin/pint -v --test

            -   name: Run tests
                run: php ./vendor/bin/pest -v --coverage-clover clover.xml

            -   uses: php-actions/phpstan@v3
                with:
                    path: src/
